CREATE SCHEMA IF NOT EXISTS lemat;
CREATE TABLE IF NOT EXISTS lemat."__MigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___MigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240827214831_Initial') THEN
    CREATE SCHEMA IF NOT EXISTS lemat;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240827214831_Initial') THEN
    CREATE TABLE lemat.suppliers (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(100) NOT NULL,
        company_reason VARCHAR(255) NULL,
        telephone text NULL,
        email text NULL,
        street text NULL,
        number text NULL,
        neighborhood text NULL,
        city text NULL,
        state text NULL,
        country text NULL,
        zip_code text NULL,
        document text NULL,
        document_type integer NULL DEFAULT 1,
        CONSTRAINT "PK_suppliers" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240827214831_Initial') THEN
    INSERT INTO lemat."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240827214831_Initial', '6.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240923211906_AddProduct') THEN
    ALTER TABLE lemat.suppliers ADD created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240923211906_AddProduct') THEN
    ALTER TABLE lemat.suppliers ADD modified_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240923211906_AddProduct') THEN
    CREATE TABLE lemat.products (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(100) NOT NULL,
        suggested_sell_price numeric NOT NULL,
        maximum_discount_percentage numeric NOT NULL,
        image_path VARCHAR(100) NULL,
        supplier_id integer NULL,
        stock_available integer NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_products" PRIMARY KEY (id),
        CONSTRAINT "FK_products_suppliers_supplier_id" FOREIGN KEY (supplier_id) REFERENCES lemat.suppliers (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240923211906_AddProduct') THEN
    CREATE INDEX "IX_products_supplier_id" ON lemat.products (supplier_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240923211906_AddProduct') THEN
    INSERT INTO lemat."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240923211906_AddProduct', '6.0.0');
    END IF;
END $EF$;
COMMIT;

