// <auto-generated />
using LeMat.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeMat.Infra.Migrations {
	[DbContext(typeof(SPContext))]
	[Migration("20240827205859_Initial")]
	partial class Initial {
		protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("LeMat.Domain.Entities.Supplier", b => {
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("integer")
					.HasColumnName("id");

				NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

				b.Property<string>("CompanyReason")
					.HasColumnType("VARCHAR(255)")
					.HasColumnName("company_reason");

				b.Property<string>("Name")
					.IsRequired()
					.HasColumnType("VARCHAR(100)")
					.HasColumnName("name");

				b.HasKey("Id");

				b.ToTable("suppliers", "spc");
			});

			modelBuilder.Entity("LeMat.Domain.Entities.Supplier", b => {
				b.OwnsOne("LeMat.Domain.ValueObjects.Address", "Address", b1 => {
					b1.Property<int>("SupplierId")
						.HasColumnType("integer");

					b1.Property<string>("City")
						.HasColumnType("text")
						.HasColumnName("city");

					b1.Property<string>("Country")
						.HasColumnType("text")
						.HasColumnName("country");

					b1.Property<string>("Neighborhood")
						.HasColumnType("text")
						.HasColumnName("neighborhood");

					b1.Property<string>("Number")
						.HasColumnType("text")
						.HasColumnName("number");

					b1.Property<string>("State")
						.HasColumnType("text")
						.HasColumnName("state");

					b1.Property<string>("Street")
						.HasColumnType("text")
						.HasColumnName("street");

					b1.Property<string>("ZipCode")
						.HasColumnType("text")
						.HasColumnName("zip_code");

					b1.HasKey("SupplierId");

					b1.ToTable("suppliers", "spc");

					b1.WithOwner()
						.HasForeignKey("SupplierId");
				});

				b.OwnsOne("LeMat.Domain.ValueObjects.Document", "Document", b1 => {
					b1.Property<int>("SupplierId")
						.HasColumnType("integer");

					b1.Property<string>("Number")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("document");

					b1.Property<int>("Type")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(1)
						.HasColumnName("document_type");

					b1.HasKey("SupplierId");

					b1.ToTable("suppliers", "spc");

					b1.WithOwner()
						.HasForeignKey("SupplierId");
				});

				b.OwnsOne("LeMat.Domain.ValueObjects.Email", "Email", b1 => {
					b1.Property<int>("SupplierId")
						.HasColumnType("integer");

					b1.Property<string>("Address")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("email");

					b1.HasKey("SupplierId");

					b1.ToTable("suppliers", "spc");

					b1.WithOwner()
						.HasForeignKey("SupplierId");
				});

				b.OwnsOne("LeMat.Domain.ValueObjects.Telephone", "Telephone", b1 => {
					b1.Property<int>("SupplierId")
						.HasColumnType("integer");

					b1.Property<string>("Number")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("telephone");

					b1.HasKey("SupplierId");

					b1.ToTable("suppliers", "spc");

					b1.WithOwner()
						.HasForeignKey("SupplierId");
				});

				b.Navigation("Address");

				b.Navigation("Document");

				b.Navigation("Email");

				b.Navigation("Telephone");
			});
#pragma warning restore 612, 618
		}
	}
}
