CREATE SCHEMA IF NOT EXISTS lemat;
CREATE TABLE IF NOT EXISTS lemat."__MigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___MigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240827214831_Initial') THEN
    CREATE SCHEMA IF NOT EXISTS lemat;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240827214831_Initial') THEN
    CREATE TABLE lemat.suppliers (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(100) NOT NULL,
        company_reason VARCHAR(255) NULL,
        telephone text NULL,
        email text NULL,
        street text NULL,
        number text NULL,
        neighborhood text NULL,
        city text NULL,
        state text NULL,
        country text NULL,
        zip_code text NULL,
        document text NULL,
        document_type integer NULL DEFAULT 1,
        CONSTRAINT "PK_suppliers" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM lemat."__MigrationsHistory" WHERE "MigrationId" = '20240827214831_Initial') THEN
    INSERT INTO lemat."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240827214831_Initial', '6.0.0');
    END IF;
END $EF$;
COMMIT;

